#!/bin/sh
# [汎用core] ハーネスダッシュボード描画 — スタック非依存
# （これはゲートでなく描画ツール＝classify の NON_GATE に登録済み・not-a-gate 扱い）
#
# WHY: 導入したゲート/ツールの「状態」を GitHub 上で一目で見たい。本スクリプトは既存のデータ源
# （classify-gate-type=型・probe-gate-liveness=生存・gate-roi-verdict=ROI判定）を **1枚の markdown 表**に
# 描画する。CI が出力を $GITHUB_STEP_SUMMARY に流せば、Actions 実行ページがそのままダッシュボードになる。
#
# 各ゲートを1行で示す: 型（prevention/detection/advisory/untyped）／生存（予防ゲートが効いているか）／
# ROI判定（keep / removal-candidate / human-judgment）。not-a-gate（ハーネスのツール）は本体から除外。
#
# Config (env):
#   DASHBOARD_DIR         ゲートの在処（既定: core/scripts→scripts）
#   DASHBOARD_FIRING_TSV  collect-gate-history の出力 TSV のパス（あれば ROI判定列を埋める・無ければ —）
#
# Usage: sh render-harness-dashboard.sh >> "$GITHUB_STEP_SUMMARY"
set -eu

ROOT="$(git -C "$(dirname -- "$0")" rev-parse --show-toplevel 2>/dev/null \
  || (CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd))"
GATE_DIR="${DASHBOARD_DIR:-}"
if [ -z "$GATE_DIR" ]; then
  if [ -d "$ROOT/core/scripts" ]; then GATE_DIR="core/scripts"; else GATE_DIR="scripts"; fi
fi
HERE="$ROOT/$GATE_DIR"
CLASSIFY="$HERE/classify-gate-type.sh"
PROBE="$HERE/probe-gate-liveness.sh"
VERDICT="$HERE/gate-roi-verdict.sh"
[ -f "$CLASSIFY" ] || { echo "_harness dashboard: classify-gate-type.sh not found in ${GATE_DIR}; skipping._"; exit 0; }

# 生存マップ（probe を1回実行・ダッシュボードは描画ツールなので DEAD があっても失敗しない）
PROBE_OUT=""
[ -f "$PROBE" ] && PROBE_OUT="$(sh "$PROBE" 2>/dev/null || true)"
liveness() {
  printf '%s\n' "$PROBE_OUT" | grep -qE "^ALIVE +$1( |\$)" && { echo "✅ ALIVE"; return 0; }
  printf '%s\n' "$PROBE_OUT" | grep -qE "^DEAD +$1( |\$)"  && { echo "❌ DEAD";  return 0; }
  echo "—"
}

# ROI判定マップ（発火 TSV があれば gate-roi-verdict で埋める）
VERD_OUT=""
if [ -n "${DASHBOARD_FIRING_TSV:-}" ] && [ -f "${DASHBOARD_FIRING_TSV:-}" ] && [ -f "$VERDICT" ]; then
  VERD_OUT="$(GATE_ROI_DIR="$GATE_DIR" sh "$VERDICT" < "$DASHBOARD_FIRING_TSV" 2>/dev/null || true)"
fi
verdict() { printf '%s\n' "$VERD_OUT" | awk -v g="$1" '$2==g {print $1; exit}'; }

# --snapshot: コミットする静的ファイル用に、スタンドアロンの見出し＋注記を前置する（リポから見えるダッシュボード）。
# 既定（job-summary 用途）は section だけを出す。生成を1箇所に集約し、ローカル生成と dashboard.yml が drift しない。
if [ "${1:-}" = "--snapshot" ]; then
  echo "# gatecrate — harness status"
  echo ""
  echo "<!-- AUTO-GENERATED by .github/workflows/dashboard.yml (render-harness-dashboard.sh --snapshot). Do not edit."
  echo "     Freshness = this file's last commit date on GitHub; the workflow opens a PR only when the table changes. -->"
  echo ""
  echo "Committed snapshot so the dashboard is visible **from the repository**. The live per-run view is on each CI"
  echo "run's Summary page; the README badge shows pass/fail. How it works: [\`docs/harness-dashboard.md\`](./harness-dashboard.md)."
  echo ""
fi

# --- collect: classify each gate, accumulate counts (type + liveness), build the table rows ---
ROWS="$(mktemp)"
prev=0; det=0; adv=0; unt=0; notg=0; alive=0; dead=0; nap=0
for g in "$HERE"/*.sh; do
  [ -f "$g" ] || continue
  base="$(basename "$g")"
  t="$(sh "$CLASSIFY" --one "$g" | awk '{print $1}')"
  case "$t" in
    prevention) prev=$((prev + 1)) ;;
    detection)  det=$((det + 1)) ;;
    advisory)   adv=$((adv + 1)) ;;
    untyped)    unt=$((unt + 1)) ;;
    *)          notg=$((notg + 1)); continue ;;   # not-a-gate / unresolved: harness tooling, not a gate
  esac
  lv="$(liveness "$base")"
  case "$lv" in *ALIVE*) alive=$((alive + 1)) ;; *DEAD*) dead=$((dead + 1)) ;; *) nap=$((nap + 1)) ;; esac
  v="$(verdict "$base")"; [ -n "$v" ] || v="—"
  ty="$t"; [ "$t" = untyped ] && ty="⚠️ untyped"
  # next action: map (type, liveness, verdict) → the maintenance step this non-final state calls for.
  na="—"
  case "$t" in
    prevention)
      case "$lv" in
        *DEAD*) na="🔴 fix — gate no longer rejects its violation" ;;
        "—")    na="add a synthetic reject injector, or mark escalation-only/not-probeable" ;;
      esac ;;
    detection)
      case "$v" in
        *removal*) na="review uniqueness (human ②); consider removing" ;;
        "—")       na="collect firing history (gh) to judge ROI" ;;
      esac ;;
    advisory)
      [ "$v" = "—" ] && na="confirm the signal is consumed (human); else downgrade/remove" ;;
    untyped) na="classify — add a \`# gatecrate-type:\` marker (or register a reject injector)" ;;
  esac
  printf '| `%s` | %s | %s | %s | %s |\n' "$base" "$ty" "$lv" "$v" "$na" >> "$ROWS"
done
# --counts: print one dated TSV row (date prev det adv unt alive dead) for the history file, then stop.
# DASHBOARD_DATE は決定論テスト用の上書き（既定は当日 UTC）。dashboard.yml がこれを history に追記する。
if [ "${1:-}" = "--counts" ]; then
  rm -f "$ROWS"
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "${DASHBOARD_DATE:-$(date -u +%F)}" "$prev" "$det" "$adv" "$unt" "$alive" "$dead"
  exit 0
fi

gates=$((prev + det + adv + unt))

if [ "$dead" -gt 0 ]; then status="❌ $dead prevention gate(s) DEAD — fix first"
elif [ "$unt" -gt 0 ]; then status="⚠️ $unt gate(s) untyped — classify them"
else status="✅ all classified · no DEAD gate"; fi

# pie slice helper: emit only non-zero slices (mermaid dislikes empty/zero), set -e safe via `|| :`.
slice() { [ "$2" -gt 0 ] && echo "    \"$1\" : $2" || :; }

echo "## 🛡️ Harness dashboard"
echo ""
echo "**$gates gates** · $status"
echo ""
echo "| metric | count |"
echo "|---|---:|"
echo "| 🛡️ prevention | $prev |"
echo "| 🎯 detection | $det |"
echo "| 📊 advisory | $adv |"
echo "| ⚠️ untyped | $unt |"
echo "| ✅ ALIVE / ❌ DEAD / — not-probed | $alive / $dead / $nap |"
echo "| 🔧 tooling (not-a-gate, excluded) | $notg |"
echo ""
echo '```mermaid'
echo 'pie showData'
echo '    title Gate types'
slice prevention "$prev"; slice detection "$det"; slice advisory "$adv"; slice untyped "$unt"
echo '```'
if [ $((alive + dead + nap)) -gt 0 ]; then
  echo ""
  echo '```mermaid'
  echo 'pie showData'
  echo '    title Prevention-gate liveness'
  slice ALIVE "$alive"; slice DEAD "$dead"; slice not-probed "$nap"
  echo '```'
fi

# --- trend: total gates over time from the accruing history (honest: needs >=2 dated rows) ---
# dashboard.yml が日次で 1 行ずつ追記する docs/harness-history.tsv（date prev det adv unt alive dead）を読む。
if [ -n "${DASHBOARD_HISTORY:-}" ] && [ -f "${DASHBOARD_HISTORY:-}" ]; then
  trend="$(awk -F '\t' '
    $1 != "" && NF >= 5 { tot[$1]=$2+$3+$4+$5; if (!($1 in seen)) { seen[$1]=1; ord[++n]=$1 } }
    END {
      if (n < 2) { print "ACCRUING\t" n; exit }
      start = (n > 12) ? n - 11 : 1
      xs=""; ys=""; max=0
      for (i = start; i <= n; i++) { k=ord[i]; xs=xs (xs==""?"":", ") "\"" substr(k,6) "\""; ys=ys (ys==""?"":", ") tot[k]; if (tot[k] > max) max=tot[k] }
      printf "CHART\t%s\t%s\t%d\n", xs, ys, max + 2
    }' "$DASHBOARD_HISTORY")"
  echo ""
  case "$trend" in
    ACCRUING*)
      echo "_Trend: accruing ($(printf '%s' "$trend" | cut -f2) day(s) recorded; the line chart appears once ≥2 dated refreshes exist)._" ;;
    CHART*)
      echo '```mermaid'
      echo 'xychart-beta'
      echo '    title "Total gates over time"'
      echo "    x-axis [$(printf '%s' "$trend" | cut -f2)]"
      echo "    y-axis \"gates\" 0 --> $(printf '%s' "$trend" | cut -f4)"
      echo "    line [$(printf '%s' "$trend" | cut -f3)]"
      echo '```' ;;
  esac
fi

# --- CI cost & firing (mermaid bars) — only when a firing TSV is supplied (collect-gate-history / gh) ---
# 高コスト × 発火0 が removal-candidate のシグナル（ROI verdict と整合）。実データには gh が要る。
if [ -n "${DASHBOARD_FIRING_TSV:-}" ] && [ -f "${DASHBOARD_FIRING_TSV:-}" ]; then
  bar_chart() {  # <title> <yaxis> <"seconds|fires"-sorted rows on stdin>
    rows="$(cat)"; [ -n "$rows" ] || return 0
    xs="$(printf '%s\n' "$rows" | awk -F '\t' '{ printf "%s\"%s\"", (NR==1?"":", "), substr($2,1,16) } END { print "" }')"
    ys="$(printf '%s\n' "$rows" | awk -F '\t' '{ printf "%s%s", (NR==1?"":", "), $1 } END { print "" }')"
    ymax="$(printf '%s\n' "$rows" | awk -F '\t' 'NR==1 { print $1 + 2 }')"
    echo '```mermaid'; echo 'xychart-beta'
    echo "    title \"$1\""
    echo "    x-axis [$xs]"; echo "    y-axis \"$2\" 0 --> $ymax"; echo "    bar [$ys]"; echo '```'
  }
  cost="$(awk -F '\t' 'NR>1 && $1!="" && $1!="gate" { sec=($5 ~ /^[0-9.]+$/)?$5+0:0; printf "%d\t%s\n", sec, $1 }' "$DASHBOARD_FIRING_TSV" | sort -nr | head -8)"
  if [ -n "$cost" ]; then
    echo ""; echo "### CI cost & firing"; echo ""
    printf '%s\n' "$cost" | bar_chart "CI cost by gate (seconds, top 8)" "seconds"
  fi
  fires="$(awk -F '\t' 'NR>1 && $1!="" && $1!="gate" && ($3+0)>0 { printf "%d\t%s\n", $3+0, $1 }' "$DASHBOARD_FIRING_TSV" | sort -nr | head -8)"
  if [ -n "$fires" ]; then
    echo ""
    printf '%s\n' "$fires" | bar_chart "Fires by gate (detection signal)" "fires"
    echo ""
    echo "_High CI cost × zero fires is the removal-candidate signal (see ROI verdict). Cost/fires from \`collect-gate-history\` (gh)._"
  fi
fi

echo ""
echo "| Gate | Type | Liveness | ROI verdict | Next action |"
echo "|---|---|---|---|---|"
cat "$ROWS"; rm -f "$ROWS"
echo ""
echo "_Liveness from \`probe-gate-liveness\` (prevention gates without a synthetic injector show \`—\`); ROI verdict from \`gate-roi-verdict\` (needs a firing TSV / gh). **Next action** turns each non-final state (\`—\` not-probed, DEAD, untyped, unavailable ROI) into the concrete maintenance step; \`—\` in that column means healthy/no action. Tooling (not-a-gate) excluded._"

# --- diagram: how each type is judged (static legend; renders as a flowchart on GitHub) ---
echo ""
echo "### How gates are judged"
echo ""
echo '```mermaid'
echo 'flowchart TD'
echo '    G(["a gate"]) --> Q{"type?"}'
echo '    Q -->|prevention| P["fires=0 is healthy · value = liveness (probe) · keep unless the guarded risk is gone"]'
echo '    Q -->|detection| D["value = firing history · long cold + costly ⇒ removal-candidate (human ②uniqueness)"]'
echo '    Q -->|advisory| V["does not block · value: is the signal consumed? · human decides"]'
echo '    Q -->|untyped| U["classify it: add a gatecrate-type marker (or register a reject injector)"]'
echo '    Q -->|not-a-gate| X["harness tooling · excluded from ROI"]'
echo '```'

# コミットされる静的スナップショット用: 生成時刻を添える（古さが見えるように）。
# job-summary 用途では未設定なので出さない（CI が DASHBOARD_GENERATED_AT を渡したときだけ）。
if [ -n "${DASHBOARD_GENERATED_AT:-}" ]; then
  echo ""
  echo "_Generated: $DASHBOARD_GENERATED_AT · auto-refreshed by \`.github/workflows/dashboard.yml\` (regenerates and opens a PR on change)._"
fi
